server:
  port: 8083
spring:
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      #cluster-nodes: 192.168.198.128:9300
      cluster-nodes: 192.168.1.103:9300
  rabbitmq:
    host: 192.168.1.103
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000 # ribbon链接超时时长
  ReadTimeout: 60000 # ribbon读取超时时间长